branches:
  - name: master
  - name: staging
    prerelease: rc

verifyConditions:
  - "@semantic-release/npm"
  - "@semantic-release/github"

prepare:
  - "@semantic-release/npm"
  - path: "@semantic-release/exec"
    cmd: |-
      yarn docker-release
  - "@semantic-release/git"

publish:
  - "@semantic-release/npm"
  - path: "@semantic-release/exec"
    cmd: |-
      yarn mdep docker tag --include_node=false -v ${nextRelease.version}
      yarn mdep docker push --include_node=false -v ${nextRelease.version}
  - "@semantic-release/github"

analyzeCommits:
  preset: angular
  releaseRules:
    - type: docs
      release: patch
    - type: refactor
      release: patch
    - type: style
      release": patch
    - type: minor
      release: minor
    - type: patch
      release: patch
    - type: major
      release: major
    - type: breaking
      release: major
