version: v1.0
name: Image builder
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804
blocks:

  - name: semantic-release
    task:
      secrets:
        - name: semantic-release
        - name: docker-hub
      prologue:
        commands:
          - checkout
          - cache restore node-modules-$(checksum yarn.lock)
      jobs:
      - name: yarn semantic-release
        commands:
        - yarn semantic-release
